### ISSUE TITLE
Facing error in cloning repo

### ISSUE THREAD

**Issue by dhruvsaidava** [ECELLGIT/ecellgit.github.io#2]
I tried to clone my git repo by using command 

git pull

**Comment by JayrajRadadiya** [comment]
@dhruvsaidava  You are doing wrong there. git pull is a cmd for getting the data that has been changed online or by other person in same repo.

Follow the steps

1)Open the Repo you want to clone.
2)then on the upper right side of screen you will find the button "Clone or Download"..
3)Now there click on the "Downlaod ZIP".
4)ZIP file will automatically download.
5)Now extract it.
6)complete you done there.
